### ISSUE TITLE
Feature request: also highlight markdown fence delimiters

### ISSUE THREAD

**Issue by mawkler** [atusy/tsnode-marker.nvim#7]
Thanks for a great plugin! I'm using the recommended configuration with `target = { 'code_fence_content' }`, and would like the lines with fence delimiters ` ``` ` to also get highlighted, just like the content inside them. Is this difficult to add?

**Comment by atusy** [comment]
Thank you for using my plugin.

`target = {"fenced_code_block"}` should save your life.

But I found there's some issues with indent. I'll try fix it.

<img width="243" alt="image" src="https://user-images.githubusercontent.com/30277794/221999973-dca33871-7f29-4074-9c8d-a574342494c9.png">

**Comment by atusy** [comment]
The above behavior comes from treesitter's parser.
To avoid it, we need some advanced technique...
I have documented it below.

https://github.com/atusy/tsnode-marker.nvim/blob/16a9d7a37c605cf36f0ac138c1ae5299e0f0dffd/doc/tsnode-marker.txt#L237-L254

**Comment by atusy** [comment]
Note that it still adds highlight on extra new line.

<img width="53" alt="image" src="https://user-images.githubusercontent.com/30277794/222013471-9eb015ff-2182-4e7e-9224-e61b52641adc.png">

**Comment by atusy** [comment]
I added `range` option which receives a function to calculate the desired range to be mark based on a node.

documented by b70f1eda9e358d2bce647c9f780fe032f72fb4e5

This should help.


<img width="220" alt="image" src="https://user-images.githubusercontent.com/30277794/222171917-83b2dcaa-6f51-4fe9-9d6a-f80ff3fa903e.png">

**Comment by mawkler** [comment]
@atusy Awesome, thank you!
