### ISSUE TITLE
feature request: disable for filetypes

### ISSUE THREAD

**Issue by jokajak** [atusy/tsnode-marker.nvim#8]
I'm using [telekasten.nvim](https://github.com/renerocksai/telekasten.nvim) which doesn't have a treesitter parser for it and I can't figure how to tell it to pretend it's markdown.

When I open a filetype of `telekasten` I get this error message.

Can tsnode-marker be enhanced to allow me to disable it for some filetypes?

Thanks in advance!

```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:32: no parser for 'telekasten' language, see :help treesitter-parsers
stack traceback:
	[C]: in function 'error'
	/usr/share/nvim/runtime/lua/vim/treesitter/language.lua:32: in function 'require_language'
	/usr/share/nvim/runtime/lua/vim/treesitter.lua:38: in function '_create_parser'
	/usr/share/nvim/runtime/lua/vim/treesitter.lua:96: in function 'get_parser'
	.../nvim/lazy/tsnode-marker.nvim/lua/tsnode-marker/init.lua:195: in function <.../nvim/lazy/tsnode-marker.nvim/lua/tsnode-marker/init.lua:193>
```

This error appears to be because tsnode-marker assumes there is a parser for the filetype and I'm not quite able to figure out how to disable this plugin when that isn't the case.

**Comment by atusy** [comment]
My example setup **explicitly** specifies the filetype as `pattern`, so that the error like yours should not happen.
If you want to omit `pattern` option, then you should check `ctx.match` which indicates the filetype.
`:h nvim_create_autocmd` will help you can find the detail about `ctx`, a table which autocmd callback receives.

```` lua
require("lazy").setup({
  {
    "atusy/tsnode-marker.nvim",
    lazy = true,
    init = function()
      vim.api.nvim_create_autocmd("FileType", {
        group = vim.api.nvim_create_augroup("tsnode-marker-markdown", {}),
        pattern = "markdown",
        callback = function(ctx)
          require("tsnode-marker").set_automark(ctx.buf, {
            target = { "code_fence_content" }, -- list of target node types
            hl_group = "CursorLine", -- highlight group
          })
        end,
      })
    end,
  },
}, {})
````

**Comment by jokajak** [comment]
Thanks, that makes sense. Using that information I determined that the filetype starts as markdown then switches to telekasten thanks to the telekasten.nvim plugin which causes things to go out of whack.

I'll see if I can figure out how to delay the evaluation to give telekasten time to set the filetype.

Thanks for this plugin, I really like it.

**Comment by atusy** [comment]
Great, and now I see your problem a bit more.
So what you want to do is not to disable for the `telekasten` filetype.
It is more like to support `telekasten`

In such a case, you can register markdown parser to `telekasten`.
If you do not need treesitter-based syntax highlights, you might also want `vim.treesitter.stop()`

``` lua
local register = vim.treesitter.language.register -- since Nvim 0.9
  or function(lang, ft)
    require("nvim-treesitter.parsers").filetype_to_parsername[ft] = lang
  end
register("telekasten", "markdown")
```
